### ISSUE TITLE
Merge mc-pi-dev image with VSCode browser image

### ISSUE THREAD

**Issue by enric1994** [sysdiglabs/program-minecraft#1]
First of all, thanks for this repository. I had an amazing time coding with my little brother.

I discovered that VSCode has a [browser version](https://github.com/cdr/code-server) (and they have Docker image!).

So I am trying to merge the `sysdiglabs/mc-pi-dev` image your provide with `codercom/code-server:latest` so my brother can code and run experiments while I host the Minecraft server remotely since VSCode has an embedded terminal.

The problem is that I don't have the Dockerfile you used for `mc-pi-dev`. Can you help?

I added this to the `docker-compose.yml` but obviously the VSCode container can't access `mc-pi-dev`:
```
vscode:
    image: codercom/code-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./code:/code
      - ./:/home/coder/.config/code-server/
    user: "1000:1000"
```

Thanks!!

Enric
